channels:
  - conda-forge
dependencies:
  - numpy
  - pocl
  - pyopencl
  - islpy
  - pip
  - pip:
    - matplotlib
    - "git+https://github.com/inducer/pymbolic.git#egg=pymbolic"
    - "git+https://github.com/inducer/loopy.git@ncsa-west-fixes#egg=loopy"
    - "git+https://github.com/inducer/pytato.git#egg=pytato"
    - "git+https://github.com/inducer/modepy.git#egg=modepy"
    - "git+https://github.com/inducer/arraycontext.git@more-ary-creation#egg=arraycontext"
    - "git+https://github.com/inducer/meshmode.git#egg=meshmode"
    - "git+https://github.com/inducer/grudge.git#egg=grudge"
